__author__ = 'Grainier Perera'
proxy_test = False
parallel_processes = 2
redis_host = 'localhost'
redis_port = '6379'
proxy_list_url = 'https://dl.dropboxusercontent.com/u/9662664/proxies.txt'
user_agent_list_url = 'https://dl.dropboxusercontent.com/u/9662664/useragents.txt'
application_index_prefix = 'application_index:'
application_data_prefix = 'application_data:'
not_updated_set_key = 'not_updated_applications'
author_urls_set_key = 'author_urls_to_index'
price_increased_applications_set_key = 'price_increased_applications'
price_decreased_applications_set_key = 'price_decreased_applications'